#ifndef BEZ_ENUM__H
#define BEZ_ENUM__H

#define LINE_SIZE 1024
#define M_PI 3.141592653589793
#define EXPAND 1
#define FILL 1
#define HOMOGENEOUS 1

typedef enum BezFileError
{
	BEZ_OK=0,
	BEZ_CONTROL_ERROR, BEZ_CURVE_ERROR, BEZ_FGETS_ERROR, BEZ_FOPEN_ERROR
}BezFileError;

typedef enum ToolId
{
	TOOL_ADD_CURVE,TOOL_DUPLICATE_CURVE,TOOL_MOVE_CURVE,TOOL_REMOVE_CURVE,
	TOOL_ADD_CONTROL,TOOL_MOVE_CONTROL,TOOL_REMOVE_CONTROL,TOOL_CLOSE_CURVE, TOOL_COLOR_CURVE,TOOL_FILL_CURVE,
	NB_TOOLS
}ToolId;
#endif
